name: .NET

on: [push]

jobs:
  build:
    strategy:
      matrix:
        dotnet: [ '3.1.x' ]
        os: [windows-latest]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - ${{ matrix.dotnet }}
    env:
      DOTNET_NOLOGO: true
    
    steps:
    - name: Getting code
      uses: actions/checkout@v1
          
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    
    - name: Build
      run: dotnet build --configuration Release --nologo
      
    - name: Try Publish Unofficial.Microsoft.mshtml.NetStandard
      run: dotnet nuget push src\Unofficial.Microsoft.mshtml.NetStandard\bin\Release\Unofficial.Microsoft.mshtml.NetStandard.*.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json; exit 0